### ISSUE TITLE
Content Length Incorrectly Calculated

### ISSUE THREAD

**Issue by TurtleWilly** [zteeed/dokuwiki-discord-notifier#10]
helper.php/ submit_payload()

* the Content-Lenght is incorrectly calculated with `mb_strlen()`. This will return the number of characters (depending on locale, etc.) rather the number of bytes. Just `strlen()` should be used here.

**Comment by zteeed** [comment]
Hello, 

You can make pull request to fix this issue, we'll review it 

Regards,
Aurélien

**Comment by TurtleWilly** [comment]
The above issue was found by simple code review in the _dokuwiki-matrix-notifier_ which was loosely based on the _dokuwiki-discord-notifier_. So I kindly informed you about our findings, since the issues stemmed from the original code. I do not have the required discord setup/ credentials to be able to test this in the context of the discord-notifier, so a pull request is impossible from my side. But the issue should be easy to spot and fix, if you look at your code. :)

**Comment by gtim** [comment]
Thank you @TurtleWilly ! Appreciated, if you discover any more issues over at matrix-notifier, you're very welcome to pass them on to us.

Cheers,
Tim
