### ISSUE TITLE
Code Duplication and Broken sendUpdate()

### ISSUE THREAD

**Issue by TurtleWilly** [zteeed/dokuwiki-discord-notifier#12]
In action.php/ `_handle` method there's a lot of duplicated code from the _helper.php_ file. Ideally this code simply should call `$helper->sendUpdate($event);` after loading the helper plugin. All the very same checks and actions are done there too.

On the other hand the helper.php/ `sendUpdate()` method is broken currently as it references a `$helper` variable that doesn't exists in the scope of the method. Should be `$this->submit_payload( );`

**Comment by zteeed** [comment]
Hello, 

You can make pull request to fix this issue, we'll review it 

Regards,
Aurélien

**Comment by gtim** [comment]
Thank you @TurtleWilly!

Cheers,
Tim

**Comment by zteeed** [comment]
it works, seems to have un issue with version which is still 1.1.1, not 1.2.0
https://i.imgur.com/m8ygyga.png
