### ISSUE TITLE
Feature Request: Disable showing "Real Name" Field

### ISSUE THREAD

**Issue by StarArmy** [zteeed/dokuwiki-discord-notifier#14]
Hello, I am requesting the addition of an option to avoid showing the "Real Name" field in Discord notifications and instead use usernames only. Showing the "real name" has caused privacy concerns on my site and my users are very concerned about it and they consider it a "leak" of personal information.

Thanks for your consideration.

**Comment by zteeed** [comment]
Hello, 

You can make pull request to fix this issue, we'll review it 

Regards,
Aurélien

**Comment by gtim** [comment]
Hi Wes @StarArmy ,

I had the same need and just merged the feature. Please let me know if it works for you.

Cheers,
Tim

**Comment by zteeed** [comment]
@gtim you may need to publish a new github release, so it's easily updated on dokuwiki plugin store

**Comment by gtim** [comment]
Thanks @zteeed ! I've published 1.2.0 now, does it look like I got it right?

**Comment by zteeed** [comment]
I'll try tonight 
Thanks
