### ISSUE TITLE
php-curl & php-mbstring

### ISSUE THREAD

**Issue by Narinyir** [zteeed/dokuwiki-discord-notifier#20]
Hi, and very thx for this plugin!
But how can i install php-curl & php-mbstring (as you wtite on the plugin page: https://www.dokuwiki.org/plugin:discordnotifier)? I'm not php programmer - googling & trying to instal is not success for me.
Can you make short video explain how to setup requirements? Best way to publish it in wikli plugin page
Great thx!

**Comment by gtim** [comment]
Hi @Narinyir,

Have you checked if php-curl is already installed? You can do this on by creating a PHP page that contains nothing but `<?=phpinfo()?>` and seeing if curl is a listed module. You could also simply install the plugin to see if it works.

I think mb-string is not a prerequisite anymore, we should update that text.

Cheers,
Tim

**Comment by Narinyir** [comment]
I check my wiki version - Release 2020-07-29 "Hogfather", check PHP version - PHP version 7.4.12
Where should i create php page and how to run it?
If i enable your plugin that i got fata error (when save page)
`Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\jenkins\DokuWikiStick\dokuwiki\lib\plugins\discordnotifier\helper.php:174 Stack trace: #0 C:\jenkins\DokuWikiStick\dokuwiki\lib\plugins\discordnotifier\action.php(40): helper_plugin_discordnotifier->submit_payload() #1 C:\jenkins\DokuWikiStick\dokuwiki\inc\Extension\EventHandler.php(81): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL) #2 C:\jenkins\DokuWikiStick\dokuwiki\inc\Extension\Event.php(93): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER') #3 C:\jenkins\DokuWikiStick\dokuwiki\inc\common.php(1411): dokuwiki\Extension\Event->advise_after() #4 C:\jenkins\DokuWikiStick\dokuwiki\inc\Action\Save.php(52): saveWikiText('beasts', '\xD0\x9E\xD1\x81\xD0\xBD\xD0\xBE\xD0\xB2\xD0\xBD\xD0\xB0\xD1...', '', false) #5 C:\jenkins\DokuWikiStick\dokuwiki\inc\ActionRouter.php(83): dokuwiki\Action\Save->preProcess() #6 C:\jenkins\DokuWikiStick\dokuwiki\inc\ActionRouter.php(48): dokuwiki\Action in C:\jenkins\DokuWikiStick\dokuwiki\lib\plugins\discordnotifier\helper.php on line 174`

**Comment by Narinyir** [comment]
how do i install php-curl?

**Comment by gtim** [comment]
@Narinyir It looks like cURL either isn't installed or isn't loaded. I'm not familiar with how it's setup on Windows, maybe [this SO answer](https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init) can help you. Hope you can figure it out.

Cheers,
Tim
