### ISSUE TITLE
Multi hooks

### ISSUE THREAD

**Issue by Rainbow-Spike** [zteeed/dokuwiki-discord-notifier#8]
I dream about multi hooks supporting

My site supports 25 language folders, and now our German translator makes massive edits, also I fix problems in all languages. So sometimes the main feed in our webhooked Discord channel become crazy

**Comment by zteeed** [comment]
seems done: https://github.com/zteeed/dokuwiki-discord-notifier/pull/15

**Comment by zteeed** [comment]
works in version 1.2.0
